language: go

go:
  - "1.x"
  # - "tip"

env:
  - GO111MODULE=on

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg

before_install:
  - go get -v -u github.com/mattn/goveralls
script:
  - go test -race -covermode=atomic -coverprofile=cover.out ./...
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=cover.out
