dist: xenial

language: go

go:
  - "1.x"
  # - "tip"

env:
  - GO111MODULE=on

services:
  - docker

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
      - docker-ce

cache:
  directories:
    - $GOPATH/pkg
    - $HOME/.cache/go-build

before_install:
  - sudo service postgresql stop
  - GO111MODULE=off go get -v -u github.com/mattn/goveralls
  - GO111MODULE=off go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
  - docker pull zikaeroh/postgres-initialized
  - docker run -d -p 127.0.0.1:5432:5432 zikaeroh/postgres-initialized
  - while ! curl http://localhost:5432 2>&1 | grep '52'; do sleep 1; done
  - migrate -database 'postgres://postgres:mysecretpassword@localhost:5432/postgres?sslmode=disable' -path internal/db/migrations up

script:
  - go test -race -covermode=atomic -coverprofile=cover.out ./...
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=cover.out
