language: go

go:
  - "1.x"
  # - "tip"

env:
  - GO111MODULE=on

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg
    - $HOME/.cache/go-build

before_install:
  - GO111MODULE=off go get -v -u github.com/mattn/goveralls
  - GO111MODULE=off go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
  - docker pull zikaeroh/postgres-initialized
  - docker run -d -p 5432:5432 zikaeroh/postgres-initialized
  - docker ps -a
  - migrate -database 'postgres://postgres:mysecretpassword@localhost:5432/postgres?sslmode=disable' -path internal/db/migrations up

script:
  - go test -race -covermode=atomic -coverprofile=cover.out ./...
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=cover.out
