language: go

go:
  - "1.x"
  # - "tip"

env:
  - GO111MODULE=on

before_install:
  - go get -v -u github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci -race -covermode=atomic
