BEGIN;

CREATE TYPE ballot_check_mode AS ENUM (
    'none',
    'ip',
    'cookie',
    'ip_and_cookie'
);

CREATE TABLE polls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT NOW() NOT NULL,
    updated_at timestamp DEFAULT NOW() NOT NULL,
    question text NOT NULL,
    choices text[],
    check_mode ballot_check_mode DEFAULT 'cookie' NOT NULL
);

CREATE TABLE ballots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT NOW() NOT NULL,
    updated_at timestamptz DEFAULT NOW() NOT NULL,
    poll_id bigint REFERENCES polls(id) NOT NULL,
    cookie text,
    ip_addr inet,
    votes bigint[]
);

COMMIT;