BEGIN;

CREATE TABLE polls (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT NOW() NOT NULL,
    updated_at timestamp DEFAULT NOW() NOT NULL,
    question text NOT NULL,
    choices text[]
);

CREATE TABLE ballots (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT NOW() NOT NULL,
    updated_at timestamp DEFAULT NOW() NOT NULL,
    poll_id int REFERENCES polls(id) NOT NULL,
    user_xid text,
    user_ip text,
    votes int[]
);

COMMIT;