BEGIN;

CREATE TABLE polls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp DEFAULT NOW() NOT NULL,
    updated_at timestamp DEFAULT NOW() NOT NULL,
    question text NOT NULL,
    choices text[]
);

CREATE TABLE ballots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT NOW() NOT NULL,
    updated_at timestamptz DEFAULT NOW() NOT NULL,
    poll_id bigint REFERENCES polls(id) NOT NULL,
    user_xid text,
    user_ip text,
    votes bigint[]
);

COMMIT;