package templates

// sh -c "gobin -m -run github.com/valyala/quicktemplate/qtc && sed -i 's://line:// line:g' *.qtpl.go && () && gofmt -s -w *.qtpl.go"
//go:generate gobin -m -run github.com/valyala/quicktemplate/qtc
//go:generate sh -c "sed -i 's://line:// line:g' *.qtpl.go"
//go:generate sh -c "sed -i 's:^//.* qtc from \\(.*\\).$:// Code generated by qtc from \\1. DO NOT EDIT.:g' *.qtpl.go"
//go:generate sh -c "gofmt -s -w *.qtpl.go"
