// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// line index.qtpl:1
package templates

// line index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// line index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

// line index.qtpl:2
type IndexPage struct {
	BasePage
	CSRF string
}

// line index.qtpl:8
func (p *IndexPage) StreamPageTitle(qw422016 *qt422016.Writer) {
	// line index.qtpl:8
	qw422016.N().S(`
	StrawRank
`)
	// line index.qtpl:10
}

// line index.qtpl:10
func (p *IndexPage) WritePageTitle(qq422016 qtio422016.Writer) {
	// line index.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
	// line index.qtpl:10
	p.StreamPageTitle(qw422016)
	// line index.qtpl:10
	qt422016.ReleaseWriter(qw422016)
	// line index.qtpl:10
}

// line index.qtpl:10
func (p *IndexPage) PageTitle() string {
	// line index.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
	// line index.qtpl:10
	p.WritePageTitle(qb422016)
	// line index.qtpl:10
	qs422016 := string(qb422016.B)
	// line index.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
	// line index.qtpl:10
	return qs422016
	// line index.qtpl:10
}

// line index.qtpl:12
func (p *IndexPage) StreamPageBody(qw422016 *qt422016.Writer) {
	// line index.qtpl:12
	qw422016.N().S(`
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="mb-3">Create your own poll!</h1>

        <p>
            Type your question and choices below.
            Voters will be able to choose and rank them as they prefer.
            Ordering does not matter; they will be randomized on the voting page.
        </p>
    </div>

    <div class="row justify-content-center">
        <div class="col-6">
            <form method="POST">
                <div class="form-group input-group-lg">
                    <input name="question" class="form-control" type="text" placeholder="Type your question here" required>
                </div>
                
                <br/>
                <!-- Replace with padding -->
                
                <div id="choice-inputs">
                    `)
	// line index.qtpl:34
	p.StreamChoice(qw422016)
	// line index.qtpl:34
	qw422016.N().S(`
                    `)
	// line index.qtpl:35
	p.StreamChoice(qw422016)
	// line index.qtpl:35
	qw422016.N().S(`
                    `)
	// line index.qtpl:36
	p.StreamChoice(qw422016)
	// line index.qtpl:36
	qw422016.N().S(`
                </div>
                
                <button class="btn btn-primary" type="submit">Submit</button>

                `)
	// line index.qtpl:41
	qw422016.N().S(p.CSRF)
	// line index.qtpl:41
	qw422016.N().S(`
            </form>

            <button class="btn btn-primary" onclick="addAnother()">Add another</button>
        </div>
    </div>
`)
	// line index.qtpl:47
}

// line index.qtpl:47
func (p *IndexPage) WritePageBody(qq422016 qtio422016.Writer) {
	// line index.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
	// line index.qtpl:47
	p.StreamPageBody(qw422016)
	// line index.qtpl:47
	qt422016.ReleaseWriter(qw422016)
	// line index.qtpl:47
}

// line index.qtpl:47
func (p *IndexPage) PageBody() string {
	// line index.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
	// line index.qtpl:47
	p.WritePageBody(qb422016)
	// line index.qtpl:47
	qs422016 := string(qb422016.B)
	// line index.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
	// line index.qtpl:47
	return qs422016
	// line index.qtpl:47
}

// line index.qtpl:49
func (p *IndexPage) StreamPageScripts(qw422016 *qt422016.Writer) {
	// line index.qtpl:49
	qw422016.N().S(`
    <script>
        var choiceInput = `)
	// line index.qtpl:51
	{
		// line index.qtpl:51
		qb422016 := qt422016.AcquireByteBuffer()
		// line index.qtpl:51
		p.WriteChoice(qb422016)
		// line index.qtpl:51
		qw422016.N().QZ(qb422016.B)
		// line index.qtpl:51
		qt422016.ReleaseByteBuffer(qb422016)
		// line index.qtpl:51
	}
	// line index.qtpl:51
	qw422016.N().S(`;

        function addAnother() {
            $("#choice-inputs").append(choiceInput);
        }
    </script>
`)
	// line index.qtpl:57
}

// line index.qtpl:57
func (p *IndexPage) WritePageScripts(qq422016 qtio422016.Writer) {
	// line index.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
	// line index.qtpl:57
	p.StreamPageScripts(qw422016)
	// line index.qtpl:57
	qt422016.ReleaseWriter(qw422016)
	// line index.qtpl:57
}

// line index.qtpl:57
func (p *IndexPage) PageScripts() string {
	// line index.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
	// line index.qtpl:57
	p.WritePageScripts(qb422016)
	// line index.qtpl:57
	qs422016 := string(qb422016.B)
	// line index.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
	// line index.qtpl:57
	return qs422016
	// line index.qtpl:57
}

// line index.qtpl:60
func (p *IndexPage) StreamChoice(qw422016 *qt422016.Writer) {
	// line index.qtpl:60
	qw422016.N().S(`
`)
	// line index.qtpl:61
	qw422016.N().S(`<div class="form-group"><input name="choice" class="form-control" type="text" placeholder="Choice" required></div>`)
	// line index.qtpl:65
	qw422016.N().S(`
`)
	// line index.qtpl:66
}

// line index.qtpl:66
func (p *IndexPage) WriteChoice(qq422016 qtio422016.Writer) {
	// line index.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
	// line index.qtpl:66
	p.StreamChoice(qw422016)
	// line index.qtpl:66
	qt422016.ReleaseWriter(qw422016)
	// line index.qtpl:66
}

// line index.qtpl:66
func (p *IndexPage) Choice() string {
	// line index.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
	// line index.qtpl:66
	p.WriteChoice(qb422016)
	// line index.qtpl:66
	qs422016 := string(qb422016.B)
	// line index.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
	// line index.qtpl:66
	return qs422016
	// line index.qtpl:66
}
