// This file is automatically generated by qtc from "vote.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// line vote.qtpl:1
package templates

// line vote.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// line vote.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

// line vote.qtpl:2
type VotePage struct {
	BasePage
	Name    string
	Choices []string
}

// line vote.qtpl:9
func (p *VotePage) StreamPageTitle(qw422016 *qt422016.Writer) {
	// line vote.qtpl:9
	qw422016.N().S(`
	StrawRank - `)
	// line vote.qtpl:10
	qw422016.E().S(p.Name)
	// line vote.qtpl:10
	qw422016.N().S(`
`)
	// line vote.qtpl:11
}

// line vote.qtpl:11
func (p *VotePage) WritePageTitle(qq422016 qtio422016.Writer) {
	// line vote.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
	// line vote.qtpl:11
	p.StreamPageTitle(qw422016)
	// line vote.qtpl:11
	qt422016.ReleaseWriter(qw422016)
	// line vote.qtpl:11
}

// line vote.qtpl:11
func (p *VotePage) PageTitle() string {
	// line vote.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
	// line vote.qtpl:11
	p.WritePageTitle(qb422016)
	// line vote.qtpl:11
	qs422016 := string(qb422016.B)
	// line vote.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
	// line vote.qtpl:11
	return qs422016
	// line vote.qtpl:11
}

// line vote.qtpl:13
func (p *VotePage) StreamPageMeta(qw422016 *qt422016.Writer) {
	// line vote.qtpl:13
	qw422016.N().S(`
	<style>
        .vote-list:empty::after {
            content: "Drag here";
            text-align: center;
            font-style: italic;
        }
    </style>
`)
	// line vote.qtpl:21
}

// line vote.qtpl:21
func (p *VotePage) WritePageMeta(qq422016 qtio422016.Writer) {
	// line vote.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	// line vote.qtpl:21
	p.StreamPageMeta(qw422016)
	// line vote.qtpl:21
	qt422016.ReleaseWriter(qw422016)
	// line vote.qtpl:21
}

// line vote.qtpl:21
func (p *VotePage) PageMeta() string {
	// line vote.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	// line vote.qtpl:21
	p.WritePageMeta(qb422016)
	// line vote.qtpl:21
	qs422016 := string(qb422016.B)
	// line vote.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	// line vote.qtpl:21
	return qs422016
	// line vote.qtpl:21
}

// line vote.qtpl:23
func (p *VotePage) StreamPageBody(qw422016 *qt422016.Writer) {
	// line vote.qtpl:23
	qw422016.N().S(`
    <div>
        <h1 style="text-align: center; padding: 3rem 1.5rem;">`)
	// line vote.qtpl:25
	qw422016.E().S(p.Name)
	// line vote.qtpl:25
	qw422016.N().S(`</h1>
    </div>

    <hr/>

    <div class="row">
        <div class="col">
            <h4 style="text-align: center">Available choices</h4>
            <br/>
            <div id="vote-unchosen" class="vote-list list-group">
                `)
	// line vote.qtpl:35
	for _, choice := range p.Choices {
		// line vote.qtpl:35
		qw422016.N().S(`
                <div class="list-group-item">`)
		// line vote.qtpl:36
		qw422016.E().S(choice)
		// line vote.qtpl:36
		qw422016.N().S(`</div>
                `)
		// line vote.qtpl:37
	}
	// line vote.qtpl:37
	qw422016.N().S(`
            </div>
        </div>

        <div class="col">
            <h4 style="text-align: center">Your choices</h4>
            <br/>
            <div id="vote-chosen" class="vote-list list-group"></div>
        </div>
    </div>
`)
	// line vote.qtpl:47
}

// line vote.qtpl:47
func (p *VotePage) WritePageBody(qq422016 qtio422016.Writer) {
	// line vote.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
	// line vote.qtpl:47
	p.StreamPageBody(qw422016)
	// line vote.qtpl:47
	qt422016.ReleaseWriter(qw422016)
	// line vote.qtpl:47
}

// line vote.qtpl:47
func (p *VotePage) PageBody() string {
	// line vote.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
	// line vote.qtpl:47
	p.WritePageBody(qb422016)
	// line vote.qtpl:47
	qs422016 := string(qb422016.B)
	// line vote.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
	// line vote.qtpl:47
	return qs422016
	// line vote.qtpl:47
}

// line vote.qtpl:49
func (p *VotePage) StreamPageScripts(qw422016 *qt422016.Writer) {
	// line vote.qtpl:49
	qw422016.N().S(`
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>

    <script>
        var unchosen = document.getElementById('vote-unchosen');
        var chosen = document.getElementById('vote-chosen');

        new Sortable(unchosen, {
            group: 'shared',
            animation: 150,
            onChange: function(evt) {
                console.log(evt);
            }
        });

        new Sortable(chosen, {
            group: 'shared',
            // chosenClass: 'active',
            animation: 150,
            onChange: function(evt) {
                console.log(evt);
            }
        });
    </script>
`)
	// line vote.qtpl:73
}

// line vote.qtpl:73
func (p *VotePage) WritePageScripts(qq422016 qtio422016.Writer) {
	// line vote.qtpl:73
	qw422016 := qt422016.AcquireWriter(qq422016)
	// line vote.qtpl:73
	p.StreamPageScripts(qw422016)
	// line vote.qtpl:73
	qt422016.ReleaseWriter(qw422016)
	// line vote.qtpl:73
}

// line vote.qtpl:73
func (p *VotePage) PageScripts() string {
	// line vote.qtpl:73
	qb422016 := qt422016.AcquireByteBuffer()
	// line vote.qtpl:73
	p.WritePageScripts(qb422016)
	// line vote.qtpl:73
	qs422016 := string(qb422016.B)
	// line vote.qtpl:73
	qt422016.ReleaseByteBuffer(qb422016)
	// line vote.qtpl:73
	return qs422016
	// line vote.qtpl:73
}
